# Generated by Django 4.0.3 on 2022-03-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
