# Generated by Django 4.0.3 on 2022-04-30 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userextend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextend',
            name='is_adult',
        ),
    ]
